### PR TITLE
Fix type error

### PR DESCRIPTION
**Pull request by jordwalke**

### CODE REVIEW

**Comment by jordwalke** [comment]
This gets the file to type check/run on 4.02.3. I don't know if I'm just doing something wrong, but feel free to just reject this PR.

**Comment by copy** [comment]
Unfortunately this breaks 4.03 and 4.04, I made this breaking change in e369d19869af41a4040d4011a7e75d2f6e3aee11. A proper fix would use cppo to differentiate between the OCaml versions. I intend to get rid of the ppx stuff anyway though, so that should fix the problem too.

**Comment by jordwalke** [comment]
We are discussing a way to allow you to respond about one version of the ast and then have it work on any compiler version. This is a great use case.

**Comment by copy** [comment]
After my recent changes 4.02 through 4.04 are now supported. In this case I decided to get rid of ppx entirely since it wasn't of great use and I can't really maintain it.

**Pull request closed without merging**
